name: CLIENTES_QA

on:
  workflow_dispatch:

env:
  aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
  aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.7.5
        terraform_wrapper: false

    - name: Debug Variables
      run: |
        echo "AWS Access Key: ${{ env.aws_access_key }}"
        echo "AWS Secret Key: ${{ env.aws_secret_key }}"

    - name: Terraform Init
      run: terraform init

    - name: Terraform Apply
      run: terraform apply -auto-approve -var="aws_access_key=${{ env.aws_access_key }}" -var="aws_secret_key=${{ env.aws_secret_key }}"

    - name: Terraform Show
      run: terraform show

    - name: Export Output
      id: tfo
      run: |
         echo "instance_ip=$(terraform output -raw instance_ip_clientesqa)" >> $GITHUB_OUTPUT

    - name: Login to Docker Hub
      run: echo ${{ secrets.DOCKER_HUB_TOKEN }} | docker login -u lukitadiscc@gmail.com --password-stdin

    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag lukytast2/t2t1:K6

    - name: Push the Docker image to Docker Hub
      run: |
          docker push lukytast2/t2t1:K6
          docker pull lukytast2/t2t1:K6

    - name: Install Docker y Start
      uses: appleboy/ssh-action@master
      with:
        host: ${{ steps.tfo.outputs.instance_ip }}
        username: ec2-user
        key: ${{ secrets.CLIENTES_KEY }}
        script: |
            sudo yum -y install docker
            sudo systemctl start docker

    - name: Pull y run de Docker
      uses: appleboy/ssh-action@master
      with:
        host: ${{ steps.tfo.outputs.instance_ip }}
        username: ec2-user
        key: ${{ secrets.CLIENTES_KEY }}
        script: |
            sudo docker pull lukytast2/t2t1:K6
            sudo docker run -d -p 8080:8080 lukytast2/t2t1:K6

    - name: Docker ps
      uses: appleboy/ssh-action@master
      with:
        host: ${{ steps.tfo.outputs.instance_ip }}
        username: ec2-user
        key: ${{ secrets.CLIENTES_KEY }}
        script: |
            sudo docker ps
